name: CI

on:
  pull_request:
    branches: [main]

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    if: github.head_ref != 'changeset-release/main'

    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install git-filter-repo
        run: |
          sudo apt-get remove -y man-db
          sudo apt-get update
          sudo apt-get install -y git-filter-repo

      - name: Install dependencies
        run: bun install

      - name: Check formatting
        run: bun run format:check

      - name: Check TypeScript
        run: bunx tsc --noEmit

      - name: Run tests
        run: find src -name "*.test.ts" -print0 | xargs -0 -n 1 -P 4 bun test

      - name: Check for unused exports
        run: bun run knip
